Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.define "db" do |db|
	  db.vm.hostname = "db"
	  db.vm.network "private_network", ip: "192.168.33.10"
  end

  #config.vm.define "www" do |www|
	#  www.vm.hostname = "www"
	#  www.vm.network "private_network", ip: "192.168.33.11"
  #end

	config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "statedb"
  end
end
