name 'statedb'
maintainer 'Gene Gotimer'
maintainer_email 'gene.gotimer@coveros.com'
license 'Apache v2.0'
description 'Installs/Configures mysql'
long_description 'Installs/Configures MySQL and a database of state names and abbreviations'
version '0.0.3'

depends 'mysql', '~> 8.5.1'
depends 'mysql2_chef_gem', '~> 2.1.0'
depends 'database', '~> 6.1.1'
depends 'httpd', '~> 0.4.5'
